name: Links checker
on: [push]
jobs:
  run_check:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: check links with mlc
        uses: becheran/mlc@v1.0.0
